### ISSUE TITLE
IT tests fail because text-field deps

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-form-layout-flow#106]
Test in module `vaadin-form-layout-flow-integration-tests` 
`com.vaadin.flow.component.formlayout.tests.FormLayoutIT.form_with_binder`  fails because of `text-field` dependency version conflict.
```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegist…t-field" has already been used with this registry
```

**Comment by denis-anisimov** [comment]
`demo` module depends on text-field SNAPSHOT .
Apparently there is another dependency to text-field.

**Comment by web-padawan** [comment]
There hasn't been any such failures recently so I assume the conflict was fixed somewhere else.
