### ISSUE TITLE
Unclear what "A form layout with custom responsive layouting" demonstrates

### ISSUE THREAD

**Issue by mickoyuh** [vaadin/vaadin-form-layout-flow#52]
Moved from Gitlab. Reported by Artur. 
--
https://vaadin.com/elements/vaadin-form-layout/java-examples
"A form layout with custom responsive layouting"

It shows three text fields. And then?

**Comment by anasmi** [comment]
Should be fixed by https://github.com/vaadin/vaadin-form-layout-flow/pull/118
