### ISSUE TITLE
simplify createFormLayoutWithBinder demo

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-form-layout-flow#57]
Form layout with binder demo could be cleaned up, clarified and simplified. It's demoing two things at once (Binder and FormLayout) and the example feels needlessly complicated. Currently the functional parts are almost 100 lines of code, that's a lot to take in at once. Some pointers from earlier conversation: 

* Comments are a bit all over the place: why is "button bar" commented but "phoneOrEmailPredicate" or most of the bindings lines not? Since this is demoing Binder, especially parts with Binder should be commented well; currently you need to know the Binder API to understand what is happening.
* Why do phone and email have the same error message if the value is not given?
* Why is valueChangeMode set to all of the TextFields? 
* Why does there need to be StringLengthValidators for firstName/lastName if they are required fields already?
* Why does doNotCall need to set to false explicitly in the reset handler?
* What's with the flashy stream operation in the else block in the click listener? 
* Why doesn't EmailValidator check for empty value?

**Comment by web-padawan** [comment]
Fixed by #120 which was merged to `2.0` branch but has to be also cherry-picked to `2.1`.

**Comment by web-padawan** [comment]
Cherry-picked by #130. Closing.
