### ISSUE TITLE
Required fields do not appear as required

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-form-layout-flow#59]
When I set a field `asRequired()` with a binder, it appears with a dot next to the label if I use outside a form, but without the dot if used withing a `FormLayout` with `FormLayout#addFormField(Component, String)`. In the latter case, it is not clear which fields are required before failing validation.

**Comment by web-padawan** [comment]
I believe this should be about using `addFormItem`. This is a known limitation.

Closing in favor of https://github.com/vaadin/vaadin-form-layout/issues/122
