### ISSUE TITLE
Add Java API for configuring the colspan of children

### ISSUE THREAD

**Issue by Legioth** [vaadin/vaadin-form-layout-flow#68]
Use of colspan is shown in e.g. https://vaadin.com/components/vaadin-form-layout/html-examples/form-layout-basic-demos#vaadin-text-fields-as-form-items. There should be a typesafe Java API for reaching the same effect. Related to https://github.com/vaadin/vaadin-form-layout-flow/issues/65.

**Comment by Legioth** [comment]
As a workaround, one can do something like `field.getElement().setAttribute("colspan", "2")`.

**Comment by enver-haase** [comment]
Suggest to add the #cols to c'tor params too with a default of 2.

**Comment by pleku** [comment]
I don't get how the colspan works, in the example mentioned there for some reason seems to be 2 columns, but how is that specified ?

The API for this could be quite straight forward in Java, but I think the columns should be then somehow specifiable for the component or otherwise it will be confusing to try to specify colspan and not see any changes.

**Comment by pleku** [comment]
Answering myself from the web component documentation:
``` 
 * By default, it makes a layout of two columns if the element width is equal or
 * wider than 40em, and a single column layout otherwise.
 * </p>
 * <p>
 * The number of columns and the responsive behavior are customizable with the
 * {@code responsiveSteps} property.
 * </p>
 * <h3>Spanning Items on Multiple Columns</h3>
 * <p>
 * You can use {@code colspan} attribute on the items. In the example below, the
 * first text field spans on two columns:
```

**Comment by pleku** [comment]
### Acceptance Criteria
- add API to `FormLayout` for `setColspan(Component component, int colspan)` where the component must be added to the layout before calling, and add a corresponding getter. Non set colspan should return 1 by default. Values less than 1 probably should not be accepted.
- add API to `FormLayout` for `add(Component component, int colspan)` which does `add(component)` and set the colspan.
- Create an demo that creates an form layout which has 3 columns (using responsive step) and has 3 rows with components that span 1, 2 and 3 columns
- Add an unit test and an integration test for the API

**Comment by svipal** [comment]
@pleku I made a PR for review
